// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/browser.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Placeholder message definitions (to be expanded in Phase 1.2)
type CreateBrowserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrowserId     string                 `protobuf:"bytes,1,opt,name=browser_id,json=browserId,proto3" json:"browser_id,omitempty"`
	Headless      bool                   `protobuf:"varint,2,opt,name=headless,proto3" json:"headless,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBrowserRequest) Reset() {
	*x = CreateBrowserRequest{}
	mi := &file_proto_browser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBrowserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBrowserRequest) ProtoMessage() {}

func (x *CreateBrowserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBrowserRequest.ProtoReflect.Descriptor instead.
func (*CreateBrowserRequest) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBrowserRequest) GetBrowserId() string {
	if x != nil {
		return x.BrowserId
	}
	return ""
}

func (x *CreateBrowserRequest) GetHeadless() bool {
	if x != nil {
		return x.Headless
	}
	return false
}

type CreateBrowserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBrowserResponse) Reset() {
	*x = CreateBrowserResponse{}
	mi := &file_proto_browser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBrowserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBrowserResponse) ProtoMessage() {}

func (x *CreateBrowserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBrowserResponse.ProtoReflect.Descriptor instead.
func (*CreateBrowserResponse) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBrowserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateBrowserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CloseBrowserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrowserId     string                 `protobuf:"bytes,1,opt,name=browser_id,json=browserId,proto3" json:"browser_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseBrowserRequest) Reset() {
	*x = CloseBrowserRequest{}
	mi := &file_proto_browser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseBrowserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseBrowserRequest) ProtoMessage() {}

func (x *CloseBrowserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseBrowserRequest.ProtoReflect.Descriptor instead.
func (*CloseBrowserRequest) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{2}
}

func (x *CloseBrowserRequest) GetBrowserId() string {
	if x != nil {
		return x.BrowserId
	}
	return ""
}

type CloseBrowserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseBrowserResponse) Reset() {
	*x = CloseBrowserResponse{}
	mi := &file_proto_browser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseBrowserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseBrowserResponse) ProtoMessage() {}

func (x *CloseBrowserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseBrowserResponse.ProtoReflect.Descriptor instead.
func (*CloseBrowserResponse) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{3}
}

func (x *CloseBrowserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CloseBrowserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NavigateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrowserId     string                 `protobuf:"bytes,1,opt,name=browser_id,json=browserId,proto3" json:"browser_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigateRequest) Reset() {
	*x = NavigateRequest{}
	mi := &file_proto_browser_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigateRequest) ProtoMessage() {}

func (x *NavigateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigateRequest.ProtoReflect.Descriptor instead.
func (*NavigateRequest) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{4}
}

func (x *NavigateRequest) GetBrowserId() string {
	if x != nil {
		return x.BrowserId
	}
	return ""
}

func (x *NavigateRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NavigateRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type NavigateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	StatusCode    int32                  `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigateResponse) Reset() {
	*x = NavigateResponse{}
	mi := &file_proto_browser_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigateResponse) ProtoMessage() {}

func (x *NavigateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigateResponse.ProtoReflect.Descriptor instead.
func (*NavigateResponse) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{5}
}

func (x *NavigateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NavigateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *NavigateResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

type GetCookiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrowserId     string                 `protobuf:"bytes,1,opt,name=browser_id,json=browserId,proto3" json:"browser_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCookiesRequest) Reset() {
	*x = GetCookiesRequest{}
	mi := &file_proto_browser_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCookiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCookiesRequest) ProtoMessage() {}

func (x *GetCookiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCookiesRequest.ProtoReflect.Descriptor instead.
func (*GetCookiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{6}
}

func (x *GetCookiesRequest) GetBrowserId() string {
	if x != nil {
		return x.BrowserId
	}
	return ""
}

func (x *GetCookiesRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetCookiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Cookies       []*Cookie              `protobuf:"bytes,3,rep,name=cookies,proto3" json:"cookies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCookiesResponse) Reset() {
	*x = GetCookiesResponse{}
	mi := &file_proto_browser_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCookiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCookiesResponse) ProtoMessage() {}

func (x *GetCookiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCookiesResponse.ProtoReflect.Descriptor instead.
func (*GetCookiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{7}
}

func (x *GetCookiesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetCookiesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetCookiesResponse) GetCookies() []*Cookie {
	if x != nil {
		return x.Cookies
	}
	return nil
}

type Cookie struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Secure        bool                   `protobuf:"varint,5,opt,name=secure,proto3" json:"secure,omitempty"`
	HttpOnly      bool                   `protobuf:"varint,6,opt,name=http_only,json=httpOnly,proto3" json:"http_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cookie) Reset() {
	*x = Cookie{}
	mi := &file_proto_browser_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cookie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cookie) ProtoMessage() {}

func (x *Cookie) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cookie.ProtoReflect.Descriptor instead.
func (*Cookie) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{8}
}

func (x *Cookie) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cookie) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Cookie) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Cookie) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Cookie) GetSecure() bool {
	if x != nil {
		return x.Secure
	}
	return false
}

func (x *Cookie) GetHttpOnly() bool {
	if x != nil {
		return x.HttpOnly
	}
	return false
}

type SetCookiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrowserId     string                 `protobuf:"bytes,1,opt,name=browser_id,json=browserId,proto3" json:"browser_id,omitempty"`
	Cookies       []*Cookie              `protobuf:"bytes,2,rep,name=cookies,proto3" json:"cookies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCookiesRequest) Reset() {
	*x = SetCookiesRequest{}
	mi := &file_proto_browser_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCookiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCookiesRequest) ProtoMessage() {}

func (x *SetCookiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCookiesRequest.ProtoReflect.Descriptor instead.
func (*SetCookiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{9}
}

func (x *SetCookiesRequest) GetBrowserId() string {
	if x != nil {
		return x.BrowserId
	}
	return ""
}

func (x *SetCookiesRequest) GetCookies() []*Cookie {
	if x != nil {
		return x.Cookies
	}
	return nil
}

type SetCookiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCookiesResponse) Reset() {
	*x = SetCookiesResponse{}
	mi := &file_proto_browser_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCookiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCookiesResponse) ProtoMessage() {}

func (x *SetCookiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCookiesResponse.ProtoReflect.Descriptor instead.
func (*SetCookiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{10}
}

func (x *SetCookiesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetCookiesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExecuteJSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrowserId     string                 `protobuf:"bytes,1,opt,name=browser_id,json=browserId,proto3" json:"browser_id,omitempty"`
	Script        string                 `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteJSRequest) Reset() {
	*x = ExecuteJSRequest{}
	mi := &file_proto_browser_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteJSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteJSRequest) ProtoMessage() {}

func (x *ExecuteJSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteJSRequest.ProtoReflect.Descriptor instead.
func (*ExecuteJSRequest) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{11}
}

func (x *ExecuteJSRequest) GetBrowserId() string {
	if x != nil {
		return x.BrowserId
	}
	return ""
}

func (x *ExecuteJSRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

type ExecuteJSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteJSResponse) Reset() {
	*x = ExecuteJSResponse{}
	mi := &file_proto_browser_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteJSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteJSResponse) ProtoMessage() {}

func (x *ExecuteJSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteJSResponse.ProtoReflect.Descriptor instead.
func (*ExecuteJSResponse) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{12}
}

func (x *ExecuteJSResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteJSResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteJSResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type SetProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrowserId     string                 `protobuf:"bytes,1,opt,name=browser_id,json=browserId,proto3" json:"browser_id,omitempty"`
	ProxyUrl      string                 `protobuf:"bytes,2,opt,name=proxy_url,json=proxyUrl,proto3" json:"proxy_url,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProxyRequest) Reset() {
	*x = SetProxyRequest{}
	mi := &file_proto_browser_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProxyRequest) ProtoMessage() {}

func (x *SetProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProxyRequest.ProtoReflect.Descriptor instead.
func (*SetProxyRequest) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{13}
}

func (x *SetProxyRequest) GetBrowserId() string {
	if x != nil {
		return x.BrowserId
	}
	return ""
}

func (x *SetProxyRequest) GetProxyUrl() string {
	if x != nil {
		return x.ProxyUrl
	}
	return ""
}

func (x *SetProxyRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SetProxyRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SetProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProxyResponse) Reset() {
	*x = SetProxyResponse{}
	mi := &file_proto_browser_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProxyResponse) ProtoMessage() {}

func (x *SetProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProxyResponse.ProtoReflect.Descriptor instead.
func (*SetProxyResponse) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{14}
}

func (x *SetProxyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetProxyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExecuteSignatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrowserId     string                 `protobuf:"bytes,1,opt,name=browser_id,json=browserId,proto3" json:"browser_id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"` // e.g., "xhs"
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteSignatureRequest) Reset() {
	*x = ExecuteSignatureRequest{}
	mi := &file_proto_browser_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSignatureRequest) ProtoMessage() {}

func (x *ExecuteSignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSignatureRequest.ProtoReflect.Descriptor instead.
func (*ExecuteSignatureRequest) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{15}
}

func (x *ExecuteSignatureRequest) GetBrowserId() string {
	if x != nil {
		return x.BrowserId
	}
	return ""
}

func (x *ExecuteSignatureRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ExecuteSignatureRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ExecuteSignatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Signatures    map[string]string      `protobuf:"bytes,3,rep,name=signatures,proto3" json:"signatures,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteSignatureResponse) Reset() {
	*x = ExecuteSignatureResponse{}
	mi := &file_proto_browser_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSignatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSignatureResponse) ProtoMessage() {}

func (x *ExecuteSignatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSignatureResponse.ProtoReflect.Descriptor instead.
func (*ExecuteSignatureResponse) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{16}
}

func (x *ExecuteSignatureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteSignatureResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteSignatureResponse) GetSignatures() map[string]string {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type ClickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrowserId     string                 `protobuf:"bytes,1,opt,name=browser_id,json=browserId,proto3" json:"browser_id,omitempty"`
	Selector      string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`                     // CSS selector (e.g., "#login-btn", ".submit-button")
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`                                  // X coordinate (used if selector is empty)
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`                                  // Y coordinate (used if selector is empty)
	TimeoutMs     int32                  `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"` // Timeout for waiting for element
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickRequest) Reset() {
	*x = ClickRequest{}
	mi := &file_proto_browser_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickRequest) ProtoMessage() {}

func (x *ClickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickRequest.ProtoReflect.Descriptor instead.
func (*ClickRequest) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{17}
}

func (x *ClickRequest) GetBrowserId() string {
	if x != nil {
		return x.BrowserId
	}
	return ""
}

func (x *ClickRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *ClickRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ClickRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ClickRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ClickResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ElementFound  bool                   `protobuf:"varint,3,opt,name=element_found,json=elementFound,proto3" json:"element_found,omitempty"` // Whether element was found (for selector-based clicks)
	ClickedX      int32                  `protobuf:"varint,4,opt,name=clicked_x,json=clickedX,proto3" json:"clicked_x,omitempty"`             // Actual X coordinate clicked
	ClickedY      int32                  `protobuf:"varint,5,opt,name=clicked_y,json=clickedY,proto3" json:"clicked_y,omitempty"`             // Actual Y coordinate clicked
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickResponse) Reset() {
	*x = ClickResponse{}
	mi := &file_proto_browser_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickResponse) ProtoMessage() {}

func (x *ClickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickResponse.ProtoReflect.Descriptor instead.
func (*ClickResponse) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{18}
}

func (x *ClickResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClickResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ClickResponse) GetElementFound() bool {
	if x != nil {
		return x.ElementFound
	}
	return false
}

func (x *ClickResponse) GetClickedX() int32 {
	if x != nil {
		return x.ClickedX
	}
	return 0
}

func (x *ClickResponse) GetClickedY() int32 {
	if x != nil {
		return x.ClickedY
	}
	return 0
}

var File_proto_browser_proto protoreflect.FileDescriptor

const file_proto_browser_proto_rawDesc = "" +
	"\n" +
	"\x13proto/browser.proto\x12\abrowser\"Q\n" +
	"\x14CreateBrowserRequest\x12\x1d\n" +
	"\n" +
	"browser_id\x18\x01 \x01(\tR\tbrowserId\x12\x1a\n" +
	"\bheadless\x18\x02 \x01(\bR\bheadless\"G\n" +
	"\x15CreateBrowserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"4\n" +
	"\x13CloseBrowserRequest\x12\x1d\n" +
	"\n" +
	"browser_id\x18\x01 \x01(\tR\tbrowserId\"F\n" +
	"\x14CloseBrowserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"a\n" +
	"\x0fNavigateRequest\x12\x1d\n" +
	"\n" +
	"browser_id\x18\x01 \x01(\tR\tbrowserId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\"c\n" +
	"\x10NavigateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode\"D\n" +
	"\x11GetCookiesRequest\x12\x1d\n" +
	"\n" +
	"browser_id\x18\x01 \x01(\tR\tbrowserId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"o\n" +
	"\x12GetCookiesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12)\n" +
	"\acookies\x18\x03 \x03(\v2\x0f.browser.CookieR\acookies\"\x93\x01\n" +
	"\x06Cookie\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x16\n" +
	"\x06secure\x18\x05 \x01(\bR\x06secure\x12\x1b\n" +
	"\thttp_only\x18\x06 \x01(\bR\bhttpOnly\"]\n" +
	"\x11SetCookiesRequest\x12\x1d\n" +
	"\n" +
	"browser_id\x18\x01 \x01(\tR\tbrowserId\x12)\n" +
	"\acookies\x18\x02 \x03(\v2\x0f.browser.CookieR\acookies\"D\n" +
	"\x12SetCookiesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"I\n" +
	"\x10ExecuteJSRequest\x12\x1d\n" +
	"\n" +
	"browser_id\x18\x01 \x01(\tR\tbrowserId\x12\x16\n" +
	"\x06script\x18\x02 \x01(\tR\x06script\"[\n" +
	"\x11ExecuteJSResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\"\x85\x01\n" +
	"\x0fSetProxyRequest\x12\x1d\n" +
	"\n" +
	"browser_id\x18\x01 \x01(\tR\tbrowserId\x12\x1b\n" +
	"\tproxy_url\x18\x02 \x01(\tR\bproxyUrl\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"B\n" +
	"\x10SetProxyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"f\n" +
	"\x17ExecuteSignatureRequest\x12\x1d\n" +
	"\n" +
	"browser_id\x18\x01 \x01(\tR\tbrowserId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\xdc\x01\n" +
	"\x18ExecuteSignatureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12Q\n" +
	"\n" +
	"signatures\x18\x03 \x03(\v21.browser.ExecuteSignatureResponse.SignaturesEntryR\n" +
	"signatures\x1a=\n" +
	"\x0fSignaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x01\n" +
	"\fClickRequest\x12\x1d\n" +
	"\n" +
	"browser_id\x18\x01 \x01(\tR\tbrowserId\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x05R\ttimeoutMs\"\x9e\x01\n" +
	"\rClickResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12#\n" +
	"\relement_found\x18\x03 \x01(\bR\felementFound\x12\x1b\n" +
	"\tclicked_x\x18\x04 \x01(\x05R\bclickedX\x12\x1b\n" +
	"\tclicked_y\x18\x05 \x01(\x05R\bclickedY2\x92\x05\n" +
	"\x0eBrowserService\x12N\n" +
	"\rCreateBrowser\x12\x1d.browser.CreateBrowserRequest\x1a\x1e.browser.CreateBrowserResponse\x12K\n" +
	"\fCloseBrowser\x12\x1c.browser.CloseBrowserRequest\x1a\x1d.browser.CloseBrowserResponse\x12?\n" +
	"\bNavigate\x12\x18.browser.NavigateRequest\x1a\x19.browser.NavigateResponse\x12E\n" +
	"\n" +
	"GetCookies\x12\x1a.browser.GetCookiesRequest\x1a\x1b.browser.GetCookiesResponse\x12E\n" +
	"\n" +
	"SetCookies\x12\x1a.browser.SetCookiesRequest\x1a\x1b.browser.SetCookiesResponse\x12B\n" +
	"\tExecuteJS\x12\x19.browser.ExecuteJSRequest\x1a\x1a.browser.ExecuteJSResponse\x12?\n" +
	"\bSetProxy\x12\x18.browser.SetProxyRequest\x1a\x19.browser.SetProxyResponse\x12W\n" +
	"\x10ExecuteSignature\x12 .browser.ExecuteSignatureRequest\x1a!.browser.ExecuteSignatureResponse\x126\n" +
	"\x05Click\x12\x15.browser.ClickRequest\x1a\x16.browser.ClickResponseB\x16Z\x14energy-service/protob\x06proto3"

var (
	file_proto_browser_proto_rawDescOnce sync.Once
	file_proto_browser_proto_rawDescData []byte
)

func file_proto_browser_proto_rawDescGZIP() []byte {
	file_proto_browser_proto_rawDescOnce.Do(func() {
		file_proto_browser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_browser_proto_rawDesc), len(file_proto_browser_proto_rawDesc)))
	})
	return file_proto_browser_proto_rawDescData
}

var file_proto_browser_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_browser_proto_goTypes = []any{
	(*CreateBrowserRequest)(nil),     // 0: browser.CreateBrowserRequest
	(*CreateBrowserResponse)(nil),    // 1: browser.CreateBrowserResponse
	(*CloseBrowserRequest)(nil),      // 2: browser.CloseBrowserRequest
	(*CloseBrowserResponse)(nil),     // 3: browser.CloseBrowserResponse
	(*NavigateRequest)(nil),          // 4: browser.NavigateRequest
	(*NavigateResponse)(nil),         // 5: browser.NavigateResponse
	(*GetCookiesRequest)(nil),        // 6: browser.GetCookiesRequest
	(*GetCookiesResponse)(nil),       // 7: browser.GetCookiesResponse
	(*Cookie)(nil),                   // 8: browser.Cookie
	(*SetCookiesRequest)(nil),        // 9: browser.SetCookiesRequest
	(*SetCookiesResponse)(nil),       // 10: browser.SetCookiesResponse
	(*ExecuteJSRequest)(nil),         // 11: browser.ExecuteJSRequest
	(*ExecuteJSResponse)(nil),        // 12: browser.ExecuteJSResponse
	(*SetProxyRequest)(nil),          // 13: browser.SetProxyRequest
	(*SetProxyResponse)(nil),         // 14: browser.SetProxyResponse
	(*ExecuteSignatureRequest)(nil),  // 15: browser.ExecuteSignatureRequest
	(*ExecuteSignatureResponse)(nil), // 16: browser.ExecuteSignatureResponse
	(*ClickRequest)(nil),             // 17: browser.ClickRequest
	(*ClickResponse)(nil),            // 18: browser.ClickResponse
	nil,                              // 19: browser.ExecuteSignatureResponse.SignaturesEntry
}
var file_proto_browser_proto_depIdxs = []int32{
	8,  // 0: browser.GetCookiesResponse.cookies:type_name -> browser.Cookie
	8,  // 1: browser.SetCookiesRequest.cookies:type_name -> browser.Cookie
	19, // 2: browser.ExecuteSignatureResponse.signatures:type_name -> browser.ExecuteSignatureResponse.SignaturesEntry
	0,  // 3: browser.BrowserService.CreateBrowser:input_type -> browser.CreateBrowserRequest
	2,  // 4: browser.BrowserService.CloseBrowser:input_type -> browser.CloseBrowserRequest
	4,  // 5: browser.BrowserService.Navigate:input_type -> browser.NavigateRequest
	6,  // 6: browser.BrowserService.GetCookies:input_type -> browser.GetCookiesRequest
	9,  // 7: browser.BrowserService.SetCookies:input_type -> browser.SetCookiesRequest
	11, // 8: browser.BrowserService.ExecuteJS:input_type -> browser.ExecuteJSRequest
	13, // 9: browser.BrowserService.SetProxy:input_type -> browser.SetProxyRequest
	15, // 10: browser.BrowserService.ExecuteSignature:input_type -> browser.ExecuteSignatureRequest
	17, // 11: browser.BrowserService.Click:input_type -> browser.ClickRequest
	1,  // 12: browser.BrowserService.CreateBrowser:output_type -> browser.CreateBrowserResponse
	3,  // 13: browser.BrowserService.CloseBrowser:output_type -> browser.CloseBrowserResponse
	5,  // 14: browser.BrowserService.Navigate:output_type -> browser.NavigateResponse
	7,  // 15: browser.BrowserService.GetCookies:output_type -> browser.GetCookiesResponse
	10, // 16: browser.BrowserService.SetCookies:output_type -> browser.SetCookiesResponse
	12, // 17: browser.BrowserService.ExecuteJS:output_type -> browser.ExecuteJSResponse
	14, // 18: browser.BrowserService.SetProxy:output_type -> browser.SetProxyResponse
	16, // 19: browser.BrowserService.ExecuteSignature:output_type -> browser.ExecuteSignatureResponse
	18, // 20: browser.BrowserService.Click:output_type -> browser.ClickResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_browser_proto_init() }
func file_proto_browser_proto_init() {
	if File_proto_browser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_browser_proto_rawDesc), len(file_proto_browser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_browser_proto_goTypes,
		DependencyIndexes: file_proto_browser_proto_depIdxs,
		MessageInfos:      file_proto_browser_proto_msgTypes,
	}.Build()
	File_proto_browser_proto = out.File
	file_proto_browser_proto_goTypes = nil
	file_proto_browser_proto_depIdxs = nil
}
