// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/browser.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BrowserService_CreateBrowser_FullMethodName    = "/browser.BrowserService/CreateBrowser"
	BrowserService_CloseBrowser_FullMethodName     = "/browser.BrowserService/CloseBrowser"
	BrowserService_Navigate_FullMethodName         = "/browser.BrowserService/Navigate"
	BrowserService_GetCookies_FullMethodName       = "/browser.BrowserService/GetCookies"
	BrowserService_SetCookies_FullMethodName       = "/browser.BrowserService/SetCookies"
	BrowserService_ExecuteJS_FullMethodName        = "/browser.BrowserService/ExecuteJS"
	BrowserService_SetProxy_FullMethodName         = "/browser.BrowserService/SetProxy"
	BrowserService_ExecuteSignature_FullMethodName = "/browser.BrowserService/ExecuteSignature"
)

// BrowserServiceClient is the client API for BrowserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BrowserService provides Energy-based browser automation
type BrowserServiceClient interface {
	// Browser lifecycle
	CreateBrowser(ctx context.Context, in *CreateBrowserRequest, opts ...grpc.CallOption) (*CreateBrowserResponse, error)
	CloseBrowser(ctx context.Context, in *CloseBrowserRequest, opts ...grpc.CallOption) (*CloseBrowserResponse, error)
	// Navigation
	Navigate(ctx context.Context, in *NavigateRequest, opts ...grpc.CallOption) (*NavigateResponse, error)
	// Cookie management
	GetCookies(ctx context.Context, in *GetCookiesRequest, opts ...grpc.CallOption) (*GetCookiesResponse, error)
	SetCookies(ctx context.Context, in *SetCookiesRequest, opts ...grpc.CallOption) (*SetCookiesResponse, error)
	// JavaScript execution
	ExecuteJS(ctx context.Context, in *ExecuteJSRequest, opts ...grpc.CallOption) (*ExecuteJSResponse, error)
	// Proxy configuration
	SetProxy(ctx context.Context, in *SetProxyRequest, opts ...grpc.CallOption) (*SetProxyResponse, error)
	// Signature execution (for platform anti-detection)
	ExecuteSignature(ctx context.Context, in *ExecuteSignatureRequest, opts ...grpc.CallOption) (*ExecuteSignatureResponse, error)
}

type browserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrowserServiceClient(cc grpc.ClientConnInterface) BrowserServiceClient {
	return &browserServiceClient{cc}
}

func (c *browserServiceClient) CreateBrowser(ctx context.Context, in *CreateBrowserRequest, opts ...grpc.CallOption) (*CreateBrowserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBrowserResponse)
	err := c.cc.Invoke(ctx, BrowserService_CreateBrowser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserServiceClient) CloseBrowser(ctx context.Context, in *CloseBrowserRequest, opts ...grpc.CallOption) (*CloseBrowserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseBrowserResponse)
	err := c.cc.Invoke(ctx, BrowserService_CloseBrowser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserServiceClient) Navigate(ctx context.Context, in *NavigateRequest, opts ...grpc.CallOption) (*NavigateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NavigateResponse)
	err := c.cc.Invoke(ctx, BrowserService_Navigate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserServiceClient) GetCookies(ctx context.Context, in *GetCookiesRequest, opts ...grpc.CallOption) (*GetCookiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCookiesResponse)
	err := c.cc.Invoke(ctx, BrowserService_GetCookies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserServiceClient) SetCookies(ctx context.Context, in *SetCookiesRequest, opts ...grpc.CallOption) (*SetCookiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCookiesResponse)
	err := c.cc.Invoke(ctx, BrowserService_SetCookies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserServiceClient) ExecuteJS(ctx context.Context, in *ExecuteJSRequest, opts ...grpc.CallOption) (*ExecuteJSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteJSResponse)
	err := c.cc.Invoke(ctx, BrowserService_ExecuteJS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserServiceClient) SetProxy(ctx context.Context, in *SetProxyRequest, opts ...grpc.CallOption) (*SetProxyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetProxyResponse)
	err := c.cc.Invoke(ctx, BrowserService_SetProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserServiceClient) ExecuteSignature(ctx context.Context, in *ExecuteSignatureRequest, opts ...grpc.CallOption) (*ExecuteSignatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteSignatureResponse)
	err := c.cc.Invoke(ctx, BrowserService_ExecuteSignature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrowserServiceServer is the server API for BrowserService service.
// All implementations must embed UnimplementedBrowserServiceServer
// for forward compatibility.
//
// BrowserService provides Energy-based browser automation
type BrowserServiceServer interface {
	// Browser lifecycle
	CreateBrowser(context.Context, *CreateBrowserRequest) (*CreateBrowserResponse, error)
	CloseBrowser(context.Context, *CloseBrowserRequest) (*CloseBrowserResponse, error)
	// Navigation
	Navigate(context.Context, *NavigateRequest) (*NavigateResponse, error)
	// Cookie management
	GetCookies(context.Context, *GetCookiesRequest) (*GetCookiesResponse, error)
	SetCookies(context.Context, *SetCookiesRequest) (*SetCookiesResponse, error)
	// JavaScript execution
	ExecuteJS(context.Context, *ExecuteJSRequest) (*ExecuteJSResponse, error)
	// Proxy configuration
	SetProxy(context.Context, *SetProxyRequest) (*SetProxyResponse, error)
	// Signature execution (for platform anti-detection)
	ExecuteSignature(context.Context, *ExecuteSignatureRequest) (*ExecuteSignatureResponse, error)
	mustEmbedUnimplementedBrowserServiceServer()
}

// UnimplementedBrowserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrowserServiceServer struct{}

func (UnimplementedBrowserServiceServer) CreateBrowser(context.Context, *CreateBrowserRequest) (*CreateBrowserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBrowser not implemented")
}
func (UnimplementedBrowserServiceServer) CloseBrowser(context.Context, *CloseBrowserRequest) (*CloseBrowserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseBrowser not implemented")
}
func (UnimplementedBrowserServiceServer) Navigate(context.Context, *NavigateRequest) (*NavigateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Navigate not implemented")
}
func (UnimplementedBrowserServiceServer) GetCookies(context.Context, *GetCookiesRequest) (*GetCookiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCookies not implemented")
}
func (UnimplementedBrowserServiceServer) SetCookies(context.Context, *SetCookiesRequest) (*SetCookiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetCookies not implemented")
}
func (UnimplementedBrowserServiceServer) ExecuteJS(context.Context, *ExecuteJSRequest) (*ExecuteJSResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteJS not implemented")
}
func (UnimplementedBrowserServiceServer) SetProxy(context.Context, *SetProxyRequest) (*SetProxyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetProxy not implemented")
}
func (UnimplementedBrowserServiceServer) ExecuteSignature(context.Context, *ExecuteSignatureRequest) (*ExecuteSignatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteSignature not implemented")
}
func (UnimplementedBrowserServiceServer) mustEmbedUnimplementedBrowserServiceServer() {}
func (UnimplementedBrowserServiceServer) testEmbeddedByValue()                        {}

// UnsafeBrowserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrowserServiceServer will
// result in compilation errors.
type UnsafeBrowserServiceServer interface {
	mustEmbedUnimplementedBrowserServiceServer()
}

func RegisterBrowserServiceServer(s grpc.ServiceRegistrar, srv BrowserServiceServer) {
	// If the following call panics, it indicates UnimplementedBrowserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrowserService_ServiceDesc, srv)
}

func _BrowserService_CreateBrowser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBrowserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServiceServer).CreateBrowser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserService_CreateBrowser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServiceServer).CreateBrowser(ctx, req.(*CreateBrowserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserService_CloseBrowser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseBrowserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServiceServer).CloseBrowser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserService_CloseBrowser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServiceServer).CloseBrowser(ctx, req.(*CloseBrowserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserService_Navigate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NavigateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServiceServer).Navigate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserService_Navigate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServiceServer).Navigate(ctx, req.(*NavigateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserService_GetCookies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCookiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServiceServer).GetCookies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserService_GetCookies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServiceServer).GetCookies(ctx, req.(*GetCookiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserService_SetCookies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCookiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServiceServer).SetCookies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserService_SetCookies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServiceServer).SetCookies(ctx, req.(*SetCookiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserService_ExecuteJS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteJSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServiceServer).ExecuteJS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserService_ExecuteJS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServiceServer).ExecuteJS(ctx, req.(*ExecuteJSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserService_SetProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServiceServer).SetProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserService_SetProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServiceServer).SetProxy(ctx, req.(*SetProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserService_ExecuteSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteSignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServiceServer).ExecuteSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserService_ExecuteSignature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServiceServer).ExecuteSignature(ctx, req.(*ExecuteSignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BrowserService_ServiceDesc is the grpc.ServiceDesc for BrowserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrowserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "browser.BrowserService",
	HandlerType: (*BrowserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBrowser",
			Handler:    _BrowserService_CreateBrowser_Handler,
		},
		{
			MethodName: "CloseBrowser",
			Handler:    _BrowserService_CloseBrowser_Handler,
		},
		{
			MethodName: "Navigate",
			Handler:    _BrowserService_Navigate_Handler,
		},
		{
			MethodName: "GetCookies",
			Handler:    _BrowserService_GetCookies_Handler,
		},
		{
			MethodName: "SetCookies",
			Handler:    _BrowserService_SetCookies_Handler,
		},
		{
			MethodName: "ExecuteJS",
			Handler:    _BrowserService_ExecuteJS_Handler,
		},
		{
			MethodName: "SetProxy",
			Handler:    _BrowserService_SetProxy_Handler,
		},
		{
			MethodName: "ExecuteSignature",
			Handler:    _BrowserService_ExecuteSignature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/browser.proto",
}
