# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import browser_pb2 as browser__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in browser_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BrowserServiceStub(object):
    """BrowserService provides Energy-based browser automation
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBrowser = channel.unary_unary(
                '/browser.BrowserService/CreateBrowser',
                request_serializer=browser__pb2.CreateBrowserRequest.SerializeToString,
                response_deserializer=browser__pb2.CreateBrowserResponse.FromString,
                _registered_method=True)
        self.CloseBrowser = channel.unary_unary(
                '/browser.BrowserService/CloseBrowser',
                request_serializer=browser__pb2.CloseBrowserRequest.SerializeToString,
                response_deserializer=browser__pb2.CloseBrowserResponse.FromString,
                _registered_method=True)
        self.Navigate = channel.unary_unary(
                '/browser.BrowserService/Navigate',
                request_serializer=browser__pb2.NavigateRequest.SerializeToString,
                response_deserializer=browser__pb2.NavigateResponse.FromString,
                _registered_method=True)
        self.GetCookies = channel.unary_unary(
                '/browser.BrowserService/GetCookies',
                request_serializer=browser__pb2.GetCookiesRequest.SerializeToString,
                response_deserializer=browser__pb2.GetCookiesResponse.FromString,
                _registered_method=True)
        self.SetCookies = channel.unary_unary(
                '/browser.BrowserService/SetCookies',
                request_serializer=browser__pb2.SetCookiesRequest.SerializeToString,
                response_deserializer=browser__pb2.SetCookiesResponse.FromString,
                _registered_method=True)
        self.ExecuteJS = channel.unary_unary(
                '/browser.BrowserService/ExecuteJS',
                request_serializer=browser__pb2.ExecuteJSRequest.SerializeToString,
                response_deserializer=browser__pb2.ExecuteJSResponse.FromString,
                _registered_method=True)
        self.SetProxy = channel.unary_unary(
                '/browser.BrowserService/SetProxy',
                request_serializer=browser__pb2.SetProxyRequest.SerializeToString,
                response_deserializer=browser__pb2.SetProxyResponse.FromString,
                _registered_method=True)
        self.ExecuteSignature = channel.unary_unary(
                '/browser.BrowserService/ExecuteSignature',
                request_serializer=browser__pb2.ExecuteSignatureRequest.SerializeToString,
                response_deserializer=browser__pb2.ExecuteSignatureResponse.FromString,
                _registered_method=True)
        self.Click = channel.unary_unary(
                '/browser.BrowserService/Click',
                request_serializer=browser__pb2.ClickRequest.SerializeToString,
                response_deserializer=browser__pb2.ClickResponse.FromString,
                _registered_method=True)


class BrowserServiceServicer(object):
    """BrowserService provides Energy-based browser automation
    """

    def CreateBrowser(self, request, context):
        """Browser lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseBrowser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Navigate(self, request, context):
        """Navigation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCookies(self, request, context):
        """Cookie management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCookies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteJS(self, request, context):
        """JavaScript execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetProxy(self, request, context):
        """Proxy configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteSignature(self, request, context):
        """Signature execution (for platform anti-detection)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Click(self, request, context):
        """Click element
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrowserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBrowser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBrowser,
                    request_deserializer=browser__pb2.CreateBrowserRequest.FromString,
                    response_serializer=browser__pb2.CreateBrowserResponse.SerializeToString,
            ),
            'CloseBrowser': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseBrowser,
                    request_deserializer=browser__pb2.CloseBrowserRequest.FromString,
                    response_serializer=browser__pb2.CloseBrowserResponse.SerializeToString,
            ),
            'Navigate': grpc.unary_unary_rpc_method_handler(
                    servicer.Navigate,
                    request_deserializer=browser__pb2.NavigateRequest.FromString,
                    response_serializer=browser__pb2.NavigateResponse.SerializeToString,
            ),
            'GetCookies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCookies,
                    request_deserializer=browser__pb2.GetCookiesRequest.FromString,
                    response_serializer=browser__pb2.GetCookiesResponse.SerializeToString,
            ),
            'SetCookies': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCookies,
                    request_deserializer=browser__pb2.SetCookiesRequest.FromString,
                    response_serializer=browser__pb2.SetCookiesResponse.SerializeToString,
            ),
            'ExecuteJS': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteJS,
                    request_deserializer=browser__pb2.ExecuteJSRequest.FromString,
                    response_serializer=browser__pb2.ExecuteJSResponse.SerializeToString,
            ),
            'SetProxy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProxy,
                    request_deserializer=browser__pb2.SetProxyRequest.FromString,
                    response_serializer=browser__pb2.SetProxyResponse.SerializeToString,
            ),
            'ExecuteSignature': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteSignature,
                    request_deserializer=browser__pb2.ExecuteSignatureRequest.FromString,
                    response_serializer=browser__pb2.ExecuteSignatureResponse.SerializeToString,
            ),
            'Click': grpc.unary_unary_rpc_method_handler(
                    servicer.Click,
                    request_deserializer=browser__pb2.ClickRequest.FromString,
                    response_serializer=browser__pb2.ClickResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'browser.BrowserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('browser.BrowserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BrowserService(object):
    """BrowserService provides Energy-based browser automation
    """

    @staticmethod
    def CreateBrowser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browser.BrowserService/CreateBrowser',
            browser__pb2.CreateBrowserRequest.SerializeToString,
            browser__pb2.CreateBrowserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseBrowser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browser.BrowserService/CloseBrowser',
            browser__pb2.CloseBrowserRequest.SerializeToString,
            browser__pb2.CloseBrowserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Navigate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browser.BrowserService/Navigate',
            browser__pb2.NavigateRequest.SerializeToString,
            browser__pb2.NavigateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCookies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browser.BrowserService/GetCookies',
            browser__pb2.GetCookiesRequest.SerializeToString,
            browser__pb2.GetCookiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCookies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browser.BrowserService/SetCookies',
            browser__pb2.SetCookiesRequest.SerializeToString,
            browser__pb2.SetCookiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteJS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browser.BrowserService/ExecuteJS',
            browser__pb2.ExecuteJSRequest.SerializeToString,
            browser__pb2.ExecuteJSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetProxy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browser.BrowserService/SetProxy',
            browser__pb2.SetProxyRequest.SerializeToString,
            browser__pb2.SetProxyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteSignature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browser.BrowserService/ExecuteSignature',
            browser__pb2.ExecuteSignatureRequest.SerializeToString,
            browser__pb2.ExecuteSignatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Click(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browser.BrowserService/Click',
            browser__pb2.ClickRequest.SerializeToString,
            browser__pb2.ClickResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
